### PR TITLE
Adds logo svg & png to docs folder, adds logo to README

### PR DESCRIPTION
**Pull request by dougbtv**
Tomo -- I've got a logo put together for koko, at least it's something for now. "koko" made me think of "coconuts" -- and I got the idea of having a coconut bouncing off of a few shipping containers, with the motion trail of the coconut "connecting the containers".

### CODE REVIEW

**Comment by s1061123** [comment]
@dougbtv thank you for your proposal for logo!
Let me take a look into it!

**Comment by s1061123** [comment]
@dougbtv Thank you again for your logo!

- Regarding the logo place, I'd put it rather in koko's wiki to in "image" folder for size reduction.
 We can refer image path from koko's wiki page.
- I also create logo candidate page and put it my modified version. I use a bit bright color.

https://github.com/redhat-nfvpe/koko/wiki/LogoCandidates

**Comment by dougbtv** [comment]
Glad that I could help with the logo, thanks for the thanks Tomo! 

Great idea having it in the wiki, that's an excellent call, feel free to close out this PR any time. Or we can use it here.

I like your color scheme a lot -- looks great, and happy to have some iteration on the logo for sure.

**Comment by s1061123** [comment]
This is already taken care of, hence it is closed. Thanks doug!

**Pull request closed without merging**
