### PR TITLE
Add veth cleanup routine in case of error

### PR DESCRIPTION
**Pull request by s1061123**
This change adds veth cleanup routine in case of error at veth
config. This comes from @networkop's comment at #42.

### CODE REVIEW

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with `ip link delete` command.

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with `ip link delete` command.

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with `ip link delete` command.

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by s1061123** [comment]
@networkop,

When one side of veth is removed, otherside is also removed because veth object must be a pair.
You can test it with following commands:

```
ip -d link show dev test1
ip -d link show dev test2
ip -d link delete test1
ip -d link show dev test2
```

**Comment by networkop** [comment]
of course, sorry, forgot about that.

**Comment by networkop** [comment]
of course, sorry, forgot about that.

**Comment by networkop** [comment]
of course, sorry, forgot about that.

**Comment by s1061123** [comment]
removed duped message (due to github system failure)

**Pull request merged**
